// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"gitee.com/flycash/permission-platform-admin/internal/web"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	cmdable := InitRedis()
	provider := InitSession(cmdable)
	rbacServiceClient := InitRBACClient()
	permissionServiceClient := InitPermissionClient()
	baseHandler := InitBaseHandler(rbacServiceClient, permissionServiceClient)
	accountHandler := web.NewAccountHandler(baseHandler)
	businessHandler := web.NewBusinessHandler(baseHandler)
	systemAdminHandler := web.NewSystemAdminHandler(baseHandler)
	component := initGinServer(provider, accountHandler, businessHandler, systemAdminHandler)
	app := &App{
		Web: component,
	}
	return app, nil
}
